### ISSUE TITLE
权限问题梳理

### ISSUE THREAD

**Issue by pillipanda** [fBloc/bloc#4]
# 各项资源存在哪些权限
## user
user 权限相关字段有 `super`，为真表示拥有全局的全部权限 + 能够进入 admin 界面

## function
function 权限相关字段有 `avaliable`，为真表示用户能够在前端看到此 function、能够被用户拖动放入 flow

## flow
flow 权限相关字段有 `read` 、 `write` 、 `execute` 、 `super` 。具体含义如下：
- read：可读此 flow（当前用户获取到的 flow 列表有此项、能够查看此 flow 具体及其运行历史）
- write ：可以更改此 flow（可以改此 flow 下的 function 构成/关系，以及每个 function 的参数输入）
- execute ：可以在前端触发运行此 flow & 可以修改此 flow 的执行控制参数(crontab、trigger_key...)
- super ：super 的权限由 2 部分构成
	- 能够分配其他用户对此 flow 的 read/write/execute/super 权限
	- 能够删除此 flow

# 开发者部署了服务后，如何给新用户用
1. 全局的 super 用户通过 admin 界面创建一个新用户的账号
2. 将此账号/名字发给对应用户
3. 对应用户即可开始使用

# 新用户的权限如何管理
上面的第 1 步 admin 界面，用户在创建新用户的时候，需要**先**为其分配拥有哪些 function 以及哪些 flow 的权限。

Q：存在的一个问题：如果开发者为其开放了某个 flow 的权限，但是其 flow 里面包含的某个 function，开发者没有为其开放权限。这种该怎么办？
A：进行联动检测这种情况并提醒开发者，然后不允许提交配置

# 老用户的权限如何管理
还是和新用户相似的界面、可以显示&管理老用户对于 function 和 flow 的权限

**Comment by pillipanda** [comment]
讨论：
function是否需要super权限？？如果不存在、想把flow开权限给某个人、但是对应人没有其中某个function的权限的话就很麻烦了。

所以两种解决：
1. 如果赋予flow权限，自动为其赋予其下全部function的权限
2. function支持super权限，从而能够开启对应的function的权限

感觉有点儿像文件和文件夹呢😂？

我目前倾向第一种

**Comment by aqeja** [comment]
# function 的权限问题

感觉function的`avaliable`有两个问题：
* 这个词的含义太宽泛，可读性一般
* 能够满足需求吗？是否需要考虑后期可能更复杂的场景：比如可以可见但不能被使用等？

# 新用户的权限
是否采取一个，额，传染的规则呢，flow都有权限了，提示用户那flow里的function也将会被分配权限，是否可行？

# function是否需要super权限
与上面的`avaliable`类似，我觉得要不用一个权限枚举字段表示？比如`permission`或者`access`为 1 ｜ 2 ｜ 3 等，同理对应其他接口的权限设置。

**Comment by richardweiu** [comment]
- super权限

我觉得 flow 中的 `super` 权限更像是 `owner` or `own` 的意思，标识这个是自己的有绝对控制权，`super` 个人感觉更像是全局的，当然从 「绝对控制权」 的角度来讲没毛病

- function是否需要super权限

其实我觉得 function 的权限应该和 flow 保持统一吧，如你所说就像文件夹和文件
让我想到 jenkins 的权限管理，是插件化的，也是可以做到分类+任务分权限提供

未来若是多团队之间共享 function 感觉更需要如此细粒度的控制

- 新用户权限

赞同在给权限的时候给予提示与选择

**Comment by pillipanda** [comment]
> 结合上面的讨论，我目前总结如下，具体再看看有没有什么问题呢：

# 各项资源存在哪些权限

## user
user 权限相关字段有 `super`，为真表示拥有全局的全部权限 + 能够进入 admin 界面

## function
function 权限相关字段有 `read` 、 `execute`，`assign_permission`。 具体含义如下：
- **read**：为真的话，能够在 flow 下面查看此 function 的运行历史
- **execute**：为真的话，用户创建新的 flow 的时候，可选择/使用此 function
- **assign_permission**：能够分配其他用户对此 function 的 read/execute/assign_permission 权限

特别说明一个情况，如果 read 为真、execute 为假：表示用户在创建自己的 flow 的时候不能使用此 function，但是能够查看已有此 function 的 flow 中的此 function 及其运行记录

## flow
flow 权限相关字段有 `read` 、 `write` 、 `execute` 、 `delete` 、 `assign_permission`。具体含义如下：
-   read：可读此 flow（当前用户获取到的 flow 列表有此项、能够查看此 flow 具体及其运行历史）
-   write ：可以更改此 flow（可以改此 flow 下的 function 构成/关系，以及每个 function 的参数输入）
-   execute ：可以在前端触发运行此 flow & 可以修改此 flow 的执行控制参数(crontab、trigger_key...)
-   **delete**：能够删除此 flow
-   **assign_permission**：能够分配其他用户对此 flow 的 read/write/execute/delete/assign_permission 权限

# 开发者部署了服务后，如何给新用户用
1.  全局的 super 用户通过 admin 界面创建一个新用户的账号
2.  将此账号/名字发给对应用户
3.  对应用户即可开始使用

# 新用户的权限如何管理
上面的第 1 步 admin 界面，用户在创建新用户的时候，需要**先**为其分配拥有哪些 function 以及哪些 flow 的权限。

Q：存在的一个问题：如果开发者为其开放了某个 flow 的权限，但是其 flow 里面包含的某个 function，开发者没有为其开放权限。这种该怎么办？  
A：**自动为对应的 function 开放 read 权限**

# 老用户的权限如何管理

还是和新用户相似的界面、可以显示&管理老用户对于 function 和 flow 的权限
